#!/usr/bin/env bash

THIS_DIR=$(cd $(dirname $0); pwd)
cd $THIS_DIR
red() {
  printf '\e[1;31m%s\n\e[0;39;49m' "$@"
}
green() {
  printf '\e[1;32m%s\n\e[0;39;49m' "$@"
}
white() {
  printf '\e[1;37m%s\n\e[0;39;49m' "$@"
}
prtred() {
	printf '\e[1;31m%s\n\e[0;39;49m' "$@"
}
prtgrn() {
	printf '\e[1;32m%s\n\e[0;39;49m' "$@"
}
prtbrown() {
	printf '\e[1;33m%s\n\e[0;39;49m' "$@"
}
login(){
red "Enter Your Bot Profile ID:"
green "ایدی تبلیغاتی خود را وارد کنید:"
read Profile
red "Enter Phone Number with pre code of country +
ex. : +989********"
green "شماره خودرا با پیش کد کشور وارد کنید
مثال : +989********"
read Phone
./tg -p tabi-$Profile --login --phone =$Phone
white "دیتای تبلیغاتی ساخته شد.برای اجرا کردن آن"
green "./tabi $Profile"
white "جهت اجرا به شکل اتولانچ هم از "
green "./tabi auto"
white "استفاده کنید"
exit
}
create() {
  name=tabi
  if [[ -e $name.lua ]] ; then
      i=1
      while [[ -e $name-$i.lua ]] ; do
          let i++
      done
      name=$name-$i
  fi
  if [[ "$i" = "3" ]] ; then
    red "This is the last one tabi"
green ".این اخرین تبلیغاتی است"
  elif [[ "$i" = "4" ]] ; then
    red "You reach maximum number tabi in this server!"
green "شما به بالاترین حد مجاز تبلیغاتی در این سرور رسیدید."
exit 1
  fi
red "Your Profile ID: $i"
green "ایدی پروفایل تبلیغاتی شما: $i"
red "Enter SUDO ID
ex. : 218722292"
green "ایدی عددی سودو را وارد کنید
مثال : 218722292"
read sudoid
redis-cli sadd "$i"owner $sudoid
red "Enter Phone Number with pre code of country +
ex. : +989********"
green "شماره خودرا با پیش کد کشور وارد کنید
+مثال : ********98"
read Phone
./tg -p tabi-$i --login --phone =$Phone
echo "" > tabi-$i.sh
exec 3<> tabi-$i.sh
    echo "while true; do" >&3
    echo "./tg -p tabi-$i -s ${HOME}/tabi/tabi-$i.lua" >&3
    echo "done" >&3
	
exec 3>&-
chmod 777 tabi-$i.sh
echo "" > tabi-$i.lua
exec 5<> tabi-$i.lua
   echo "tablighati = '"$i"'" >&5
    echo "function stags()" >&5
    echo "tablighatif = dofile('tabi.lua')" >&5
	    echo "end" >&5
    echo "stags()" >&5
exec 5>&-
white "تبلیغاتی شما ساخته شد.برای اجرا کردن آن"
green "./tabi $i"
white "جهت اجرا به شکل اتولانچ هم از "
green "./tabi auto"
white "استفاده کنید"
exit
}
usage() {
printf "\e[1;36m"
  cat <<EOF
راهنمای استفاده از راه انداز تبلیغاتی
:گزینه ها
./tabi create
ساخت تبلیغاتی جدید
./tabi install
نصب پیش نیاز های تبلیغاتی
./tabi login
ورود به یک تبلیغاتی از قبل ساخته شده
./tabi help
نمایش این متن
./tabi clear
پاک سازی یک تبلیغاتی
./tabi setlicense
تنظیم لایسنس سرور
./tabi contactus
نمایش راه های ارتباطی
./tabi update
بروزرسانی سورس در صورت موجود بودن
./tabi addsudo
افزودن یک سودو برای تبلغاتی
./tabi gettg
دریافت کتابخانه مخصوص
./tabi auto
راه اندازی اتولانچ
EOF
printf "%s\n\e[0;39;49m"
}
setlicense(){
 red "Enter Your License Code(26 word):
ex. : Qweasdzxc987321456Aqzwsxrf"
green "کد لایسنس خود را وارد کنید(شامل 26 حرف):
مثال : Qweasdzxc987321456Aqzwsxrf"
read license
redis-cli set LicenseCheck $license
red "Your License seted and checked when you run a tabi"
green "لایسنس شما تنظیم شد و وقتی تبلیغاتی اجرا میشود بررسی خواهد شد"
  exit
}
contactus(){
 red "Our Contact way:"
green "Channel: @Stags"
green "Developer: @CaltMan"
green "Robot: @StagsBot"
 red "راه های ارتباط باما:"
green "کانال: @Stags"
green "توسعه دهنده: @CaltMan"
green "ربات: @StagsBot"
  exit
}
update(){
 red "Enter User:"
 green "نام کاربری خود را وارد کنید:"
read Username
 red "Enter Pass:"
 green "رمز خود را وارد کنید:"
read Password
 wget "http://update.stags.ir/tabi.lua" --user=$Username --password=$Password -O tabi.lua
 red "Updated Compeleted!"
green "عملیات بروزرسانی انجام شد!"
  exit
}
gettg(){
 red "Enter Url:"
 green "آدرس خود را وارد کنید:"
read Urlget
 wget "$Urlget" -O tg
 chmod +x tg
 red "TG geted!"
green "عملیات انجام شد!"
  exit
}
addsudo(){
 red "Enter Tablighati ID:"
 green "ایدی تبلیغاتی موردنظر را واردکنید:"
read TabID
 red "Enter SUDO ID:"
 green "ایدی سودوی مورد نظر را وارد کنید:"
read SudoID
redis-cli sadd "$SudoID"owner $TabID
  exit
}
clear() {
  green '
       شماره تبلیغاتیی که میخواهید آن را حذف کنید وارد کنید
'
  read -rp ' ' ID
  rm -rf ~/.tg/tabi-"$ID"
  rm -rf tabi-"$ID".lua
 rm -rf tabi-"$ID".sh
  rm -rf rm -rf ~/.telegram-bot/tabi-"$ID"
  red '
     تبلیغاتی شماره '$ID' با موفقیت حذف شد
'
  exit
}
autolaunch() {
while true ; do
    for tabi in tabi-*.sh ; do
      tab="${tabi%.*}"
      ltab="${tab/-/ }"
screen -S $tab -X quit
screen -d -m -S $tab ./$tab.sh
rm -rf ~/.telegram-bot/$tab/files
rm -rf ~/.telegram-bot/$tab/data/temp 
rm -rf ~/.telegram-bot/$tab/data/secret_thumbnails 
rm -rf ~/.telegram-bot/$tab/data/secret 
rm -rf ~/.telegram-bot/$tab/data/profile_photos 
rm -rf ~/.telegram-bot/$tab/data/thumbnails 
rm -rf ~/.telegram-bot/$tab/data/stickers 
rm -rf ~/.telegram-bot/$tab/data/wallpapers     
    done
	echo -e "\e[1;32m WRITTEN BY: @CaltMan in @Stags\n\e[0;39;49m"
	echo -e "\e[1;32m TABLIGHATI V2.3\n\e[0;39;49m"
    sleep 300
done
  while true ; do
for tabi in tabi-*.sh ; do
      tab="${tabi%.*}"
      ltab="${tab/-/ }"
rm -rf ~/.telegram-bot/$tab/data/db.sqlite
  sleep 6000
  done
done
}
install() {
prtgrn '
   *//Do you want to install Essentials of Tablighati? (Y/N):
 '
	read -rp ' ' install
	case "$install" in
    Y|y|بله)
 
 prtgrn '
	*//Change Nameservers to Google:
 '
	sudo echo "nameserver 8.8.8.8" | sudo tee /etc/resolv.conf > /dev/null
	chmod +x tg
	prtgrn '
 *//Updating old packages:
 '
sudo apt-get -y update && sudo apt-get -y upgrade 
prtgrn '
 *//Installing Essentials packages:
 '
	sudo apt-get --force-yes install git wget screen tmux libconfig++9v5 libconfig9 libevent-dev libjansson4 libstdc++6 lua-socket lua5.2 liblua5.2 make unzip redis-server software-properties-common g++ libconfig++-dev
	sudo apt-get -y update && sudo apt-get -y upgrade
 sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test && sudo apt-get -y update && sudo apt-get --force-yes install gcc-4.9 g++-4.9 && sudo update-alternatives —install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 —slave /usr/bin/g++ g++ /usr/bin/g++-4.9
prtgrn '
 *//Updating packages:
 '
	sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y dist-upgrade && sudo apt-get -y autoremove
	prtgrn '
 *//Restarting redis service:
 '
	sudo service redis-server restart
	white '
تبلیغاتی نصب شد.حال برای راه اندازی از دستور 
./tabi create
استفاده کنید'
green '
برای دریافت لیست لانچر دستور
./tabi help
راارسال کنید'
 ;;
    N|n|خیر)
		prtbrown '
        لغو عملیات
 Canceling the operation
 '
    ;;
    *)
		prtred '
    دستور اشتباه
  Wrong command
 '
		install
    ;;
esac
}
auto() {
	killall screen
screen ./tabi autolaunch
}

case $1 in
  create)
    create
  ;;
  install)
    install
  ;;
    setlicense)
    setlicense
  ;;
  contactus)
    contactus
	  ;;
  gettg)
    gettg
  ;;
  update)
    update
	 ;;
	   addsudo)
    addsudo
	 ;;
    clear)
    clear
  ;;
  login)
    login
  ;;
  autolaunch)
    autolaunch
  ;;
    auto)
    auto
  ;;
  help)
    usage
  ;;
  a*)
    id="${1/a/}"
    if [ -a "$THIS_DIR"/tabi-"$id".sh ]; then
      screen -x -s tabi-"$id" quit
      while true ; do
        screen -s tabi-"$id" ./tabi-"$id".sh
        sleep 10
      done
    else
      usage
    fi
  ;;
  clr)
    clear
  ;;
  *)
    if [ -a "$THIS_DIR"/tabi-"$1".sh ]; then
      ./tabi-"$1".sh
    else
    usage
    fi
  ;;
esac
